# Generated by Django 4.2.4 on 2023-08-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_file', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hired_Employee',
            new_name='HiredEmployee',
        ),
    ]
